# Generated by Django 3.0.7 on 2020-06-30 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_auto_20200630_2021'),
        ('app', '0002_auto_20200629_2233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
