# Generated by Django 3.0.7 on 2020-07-01 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200701_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=200)),
                ('completedness', models.IntegerField(default='1')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Task')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
